#!/bin/sh /etc/rc.common
# First start irqbalance
# Try to balance manually both eth to core2 and wifi0 to core2 ifthey are not balanced correctly
# System -> startup -> Local Startup
#  /etc/init.d/set_cpu_affinity

START=99

set_irq_affinity() {
	local name="$1"
	local val="$2"

case "$name" in
wifi0)
  	local irq_wifi0=`grep -E -m1 'ath10k_ahb|qcom-pcie-msi' /proc/interrupts | cut -d: -f1 | tail -n1 | tr -d ' '`
	[ -n "$irq_wifi0" ] || echo "$name irq not found."
	echo "$val" > "/proc/irq/$irq_wifi0/smp_affinity"
	;;
wifi1)
  	local irq_wifi1=`grep -E -m2 'ath10k_ahb|qcom-pcie-msi' /proc/interrupts | cut -d: -f1 | tail -n1 | tr -d ' '`
	[ -n "$irq_wifi1" ] || echo "$name irq not found."
	echo "$val" > "/proc/irq/$irq_wifi1/smp_affinity"
	;;
eth0)
  	local irq_eth0=`grep -E -m3 'eth0' /proc/interrupts | cut -d: -f1 | tail -n1 | tr -d ' '`
	[ -n "$irq_eth0" ] || echo "$name irq not found."
	echo "$val" > "/proc/irq/$irq_eth0/smp_affinity"
	;;
eth1)
  	local irq_eth1=`grep -E -m3 'eth1' /proc/interrupts | cut -d: -f1 | tail -n1 | tr -d ' '`
	[ -n "$irq_eth1" ] || echo "$name irq not found."
	echo "$val" > "/proc/irq/$irq_eth1/smp_affinity"
	;;
*)
  	local irq=`grep -m 1 "$name" /proc/interrupts | cut -d: -f1 | sed 's, *,,'`
	[ -n "$irq" ] || echo "$name irq not found."
	echo "$val" > "/proc/irq/$irq/smp_affinity"
	;;
esac
}

start() {
	. /lib/functions.sh

	/usr/sbin/irqbalance

	# WAN and 802.11AC wifi on separate cores
	set_irq_affinity eth0 1
	set_irq_affinity wifi0 1

	# LAN and 802.11b/g/n on separate cores (and balanced - one wifi chip per core, one network chip per core)
	set_irq_affinity eth1 1
	set_irq_affinity wifi1 2
}
